basic:
  controller_image_name: "bj-sm-ai-registry.cn-beijing.cr.aliyuncs.com/ai-deploy/common/vc-controller-manager"
  scheduler_image_name: "bj-sm-ai-registry.cn-beijing.cr.aliyuncs.com/ai-deploy/common/vc-scheduler"
  admission_image_name: "bj-sm-ai-registry.cn-beijing.cr.aliyuncs.com/ai-deploy/common/vc-webhook-manager"
  admission_secret_name: "volcano-admission-secret"
  admission_config_file: "config/volcano-admission.conf"
  scheduler_config_file: "config/volcano-scheduler.conf"
  image_pull_secret: ""
  image_pull_policy: "IfNotPresent"
  image_tag_version: "latest"
  admission_port: 8443
custom:
  metrics_enable: false
  admission_enable: true
  admission_replicas: 1
  controller_enable: true
  controller_replicas: 1
  scheduler_enable: true
  scheduler_replicas: 1
  enabled_admissions: "/jobs/mutate,/jobs/validate,/podgroups/mutate,/pods/validate,/pods/mutate,/queues/mutate,/queues/validate"
